### ISSUE TITLE
Indexing by peer and by sender inst working properly. 

### ISSUE THREAD

**Issue by MbBrainz** [MbBrainz/p2p-nft-trade#11]
*Code is in branch: release/1.0.0* 
The multindex of Sender and peer doesnt seem to work properly. In test "test_query_indices", we inject an offer in the database, and we query offers for both sender and peer (should both return 1 offer). However query_offers_by_peer and .._by_sender both return 0 offers. The asserts in line 199 and 200 both fail.

"test_query_indices" -> asserts in line 199 and 200 fail
https://github.com/pegasuszone/pegasus/blob/b3cc162e331e726d0bbf26a09a5da9af764b6935/src/unit_tests.rs#L175-L201

query functions
https://github.com/pegasuszone/pegasus/blob/b3cc162e331e726d0bbf26a09a5da9af764b6935/src/query.rs#L19-L40

indices definition
https://github.com/pegasuszone/pegasus/blob/b3cc162e331e726d0bbf26a09a5da9af764b6935/src/state.rs#L67-L89

**Comment by josefleventon** [comment]
Fixed in release/1.0.0
